#
# Copyright 2015 GMRR
#

##################################################
# GMRR Sources
##################################################
GMRR_SRCS = $(abspath $(addprefix $(BASE_DIR)/../lib/gmrr/, \
noc_block_delay.v \
noc_block_integrated_predistorter.v \
delay_better.v \
predistort.v \
ram_to_fifo_next.v \
ram_2port_next.v \
))
