#
# Copyright 2015 GMRR
#

##################################################
# GMRR Sources
##################################################
GMRR_SRCS = $(abspath $(addprefix $(BASE_DIR)/../lib/gmrr/, \
noc_block_gain.v \
noc_block_mult.v \
noc_block_magphase_gain.v \
noc_block_predistort.v \
predistort.v \
ram_to_fifo_next.v \
ram_2port_next.v \
))
